#ifndef PSANA_ARCHON_DDL_H
#define PSANA_ARCHON_DDL_H 1

// *** Do not edit this file, it is auto-generated ***

#include <vector>
#include <iosfwd>
#include <cstring>
#include "ndarray/ndarray.h"
#include "pdsdata/xtc/TypeId.hh"
namespace Psana {
} // namespace Psana
#endif // PSANA_ARCHON_DDL_H
