
// *** Do not edit this file, it is auto-generated ***

#include <cstddef>
#include "psddl_psana/epix.ddl.h"
#include <iostream>
namespace Psana {
namespace Epix {

AsicConfigV1::~AsicConfigV1() {}


ConfigV1::~ConfigV1() {}


Asic10kConfigV1::~Asic10kConfigV1() {}


Config10KV1::~Config10KV1() {}


Asic100aConfigV1::~Asic100aConfigV1() {}


Config100aV1::~Config100aV1() {}


Config100aV2::~Config100aV2() {}


Asic10kaConfigV1::~Asic10kaConfigV1() {}


Config10kaV1::~Config10kaV1() {}


ElementV1::~ElementV1() {}


ElementV2::~ElementV2() {}


ElementV3::~ElementV3() {}

} // namespace Epix
} // namespace Psana
