
// *** Do not edit this file, it is auto-generated ***

#include <cstddef>
#include "psddl_psana/uxi.ddl.h"
#include <iostream>
namespace Psana {
namespace Uxi {

ConfigV1::~ConfigV1() {}


FrameV1::~FrameV1() {}

} // namespace Uxi
} // namespace Psana
